# Generated by Django 5.0.6 on 2024-06-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
    ]
