# Generated by Django 5.0.6 on 2024-06-07 01:09

from django.db import migrations

def populate_team(apps, schemaeditor):
    entries = {
        "Alpha": "team 1",
        "Bravo": "team 2",
        "Charlie": "team 3"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()
        
def populate_role(apps, schemaeditor):
    entries = {
        "developer": "team members who execute the work defined in issues",
        "scum master": "the team's coach",
        "product owner": "the person on the team who defines what is built"
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_team),
        migrations.RunPython(populate_role)
    ]
